apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: mixed-arch-pool
spec:
  template:
    spec:
      requirements:
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64", "arm64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot", "on-demand"]
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: ["c7g.large", "t3.large", "t4g.medium", "m6g.medium"]
      kubeletConfiguration:
        containerRuntime: containerd
      limits:
        resources:
          cpu: "1000m" 
  disruption:
    consolidateAfter: 30s
    expireAfter: 720h
  strategy:
    spotFallback: true
